#!/usr/bin/env python3
"""Q-Voice — local wake-word style voice loop for Quantic OS.

Audio never leaves the machine. Speech recognition is performed with
whisper.cpp, responses are generated by Q-Agent/Ollama, and speech synthesis
uses Piper when available with an espeak-ng fallback.

The daemon never executes privileged shell commands. It only converses and
writes local state files for the Quantic UI/companion layer.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import tempfile
import time
from pathlib import Path

from qagent import ask
from qmodelhub import choose_model

STATE = Path(os.environ.get("QUANTIC_VOICE_STATE", str(Path.home() / ".local/share/quantic")))
WHISPER_MODEL = Path(os.environ.get("QUANTIC_WHISPER_MODEL", "/usr/share/quantic/models/ggml-base.bin"))
PIPER_MODEL = Path(os.environ.get("QUANTIC_PIPER_MODEL", "/usr/share/quantic/models/fr_FR-siwis-medium.onnx"))
WAKE_WORDS = ("quantic", "hey quantic", "salut quantic", "q ")


def run(cmd: list[str], *, input_text: str | None = None, timeout: int = 120) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, input=input_text, text=True, capture_output=True, timeout=timeout, check=False)


def recorder() -> list[str] | None:
    if shutil.which("pw-record"):
        return ["pw-record", "--rate", "16000", "--channels", "1", "--format", "s16", "--"]
    if shutil.which("arecord"):
        return ["arecord", "-q", "-f", "S16_LE", "-r", "16000", "-c", "1"]
    return None


def whisper_bin() -> str | None:
    for name in ("whisper-cli", "whisper-cpp", "main"):
        p = shutil.which(name)
        if p:
            return p
    return None


def capture(seconds: int = 5) -> Path | None:
    rec = recorder()
    if not rec:
        return None
    fd, name = tempfile.mkstemp(prefix="quantic-", suffix=".wav")
    os.close(fd)
    path = Path(name)
    if Path(rec[0]).name == "pw-record":
        cmd = rec + [str(path)]
        proc = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        time.sleep(seconds)
        proc.terminate()
        try:
            proc.wait(timeout=2)
        except subprocess.TimeoutExpired:
            proc.kill()
    else:
        cmd = rec + ["-d", str(seconds), str(path)]
        run(cmd, timeout=seconds + 5)
    return path if path.exists() and path.stat().st_size > 1000 else None


def transcribe(audio: Path) -> str:
    wb = whisper_bin()
    if not wb or not WHISPER_MODEL.exists():
        return ""
    p = run([wb, "-m", str(WHISPER_MODEL), "-f", str(audio), "-l", "fr", "-nt", "-np"], timeout=90)
    text = (p.stdout or "").strip()
    if not text:
        text = (p.stderr or "").strip()
    lines = [x.strip() for x in text.splitlines() if x.strip() and not x.strip().startswith("[")]
    return " ".join(lines).strip()


def speak(text: str) -> None:
    text = text.strip()
    if not text:
        return
    piper = shutil.which("piper")
    if piper and PIPER_MODEL.exists():
        with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
            out = Path(f.name)
        try:
            proc = run([piper, "--model", str(PIPER_MODEL), "--output_file", str(out)], input_text=text, timeout=90)
            if proc.returncode == 0 and out.exists():
                player = shutil.which("pw-play") or shutil.which("aplay")
                if player:
                    run([player, str(out)], timeout=90)
                    return
        finally:
            out.unlink(missing_ok=True)
    espeak = shutil.which("espeak-ng")
    if espeak:
        run([espeak, "-v", "fr-fr", "-s", "168", "-p", "38", text], timeout=90)


def write_state(**payload: object) -> None:
    STATE.mkdir(parents=True, exist_ok=True)
    payload["updated_at"] = int(time.time())
    tmp = STATE / "voice-state.json.tmp"
    tmp.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    tmp.replace(STATE / "voice-state.json")


def clean_transcript(text: str) -> str:
    t = " ".join(text.replace("\n", " ").split())
    return t.strip(" .")


def is_wake(text: str) -> bool:
    low = text.lower()
    return any(w in low for w in WAKE_WORDS)


def strip_wake(text: str) -> str:
    low = text.lower()
    for w in WAKE_WORDS:
        idx = low.find(w)
        if idx >= 0:
            return text[idx + len(w):].lstrip(" ,:;.-")
    return text


def answer(prompt: str) -> str:
    model = choose_model("chat")
    if not model:
        return "Mon cerveau local n'est pas encore chargé. Le modèle Quantic doit être installé."
    try:
        return ask(model, prompt, "http://127.0.0.1:11434")
    except SystemExit as exc:
        return f"Je n'arrive pas encore à joindre mon moteur local. {exc}"


def daemon(chunk_seconds: int = 5, active_window: int = 45) -> None:
    STATE.mkdir(parents=True, exist_ok=True)
    active_until = 0.0
    write_state(status="ready", listening=True, message="Dis « Quantic » pour me parler.")
    while True:
        audio = capture(chunk_seconds)
        if not audio:
            write_state(status="audio-unavailable", listening=False)
            time.sleep(3)
            continue
        try:
            text = clean_transcript(transcribe(audio))
        finally:
            audio.unlink(missing_ok=True)
        if not text:
            continue
        now = time.time()
        awakened = is_wake(text)
        if awakened:
            active_until = now + active_window
            text = strip_wake(text)
            if not text:
                speak("Oui ?")
                write_state(status="awake", listening=True, transcript="Quantic", response="Oui ?")
                continue
        if now > active_until:
            continue
        if len(text) < 2:
            continue
        write_state(status="thinking", listening=False, transcript=text)
        response = answer(text)
        write_state(status="speaking", listening=False, transcript=text, response=response)
        speak(response)
        active_until = time.time() + active_window
        write_state(status="ready", listening=True, transcript=text, response=response)


def main() -> None:
    p = argparse.ArgumentParser(description="Quantic local voice companion")
    p.add_argument("--daemon", action="store_true")
    p.add_argument("--say", help="Speak a sentence through the local TTS stack")
    p.add_argument("--once", action="store_true", help="Capture one utterance and answer")
    args = p.parse_args()
    if args.say:
        speak(args.say)
        return
    if args.once:
        audio = capture(6)
        if not audio:
            raise SystemExit("No microphone recorder available")
        try:
            text = clean_transcript(transcribe(audio))
        finally:
            audio.unlink(missing_ok=True)
        print(text)
        if text:
            response = answer(text)
            print(response)
            speak(response)
        return
    daemon()


if __name__ == "__main__":
    main()
